package com.example.bo4e.enums;

import java.io.IOException;

/**
 * Auflistung möglicher abzurechnender Dienstleistungen.
 */
public enum Dienstleistungstyp {
    ABLESUNG_HALBJAEHRLICH, ABLESUNG_JAEHRLICH, ABLESUNG_MONATLICH, ABLESUNG_VIERTELJAEHRLICH, ABLESUNG_ZUSAETZLICH_KUNDE, ABLESUNG_ZUSAETZLICH_MSB, AUSLESUNG_2_X_TAEGLICH_FERNAUSLESUNG, AUSLESUNG_FERNAUSLESUNG, AUSLESUNG_FERNAUSLESUNG_ZUSAETZLICH_MSB, AUSLESUNG_JAEHRLICH_FERNAUSLESUNG, AUSLESUNG_KOMPAKTMENGENUMWERTER, AUSLESUNG_MANUELL_MSB, AUSLESUNG_MDE, AUSLESUNG_MOATLICH_FERNAUSLESUNG, AUSLESUNG_MONATLICH_FERNAUSLESUNG, AUSLESUNG_STUENDLICH_FERNAUSLESUNG, AUSLESUNG_SYSTEMMENGENUMWERTER, AUSLESUNG_TAEGLICH_FERNAUSLESUNG, AUSLESUNG_TEMPERATURMENGENUMWERTER, AUSLESUNG_VORGANG, AUSLESUNG_ZUSTANDSMENGENUMWERTER, DATENBEREITSTELLUNG_EINMALIG, DATENBEREITSTELLUNG_HALBJAEHRLICH, DATENBEREITSTELLUNG_HISTORISCHE_LG, DATENBEREITSTELLUNG_JAEHRLICH, DATENBEREITSTELLUNG_MONATLICH, DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH, DATENBEREITSTELLUNG_STUENDLICH, DATENBEREITSTELLUNG_TAEGLICH, DATENBEREITSTELLUNG_VIERTELJAEHRLICH, DATENBEREITSTELLUNG_WOECHENTLICH, ENTSPERRUNG, INKASSOKOSTEN, MAHNKOSTEN, SPERRUNG;

    public String toValue() {
        switch (this) {
            case ABLESUNG_HALBJAEHRLICH: return "ABLESUNG_HALBJAEHRLICH";
            case ABLESUNG_JAEHRLICH: return "ABLESUNG_JAEHRLICH";
            case ABLESUNG_MONATLICH: return "ABLESUNG_MONATLICH";
            case ABLESUNG_VIERTELJAEHRLICH: return "ABLESUNG_VIERTELJAEHRLICH";
            case ABLESUNG_ZUSAETZLICH_KUNDE: return "ABLESUNG_ZUSAETZLICH_KUNDE";
            case ABLESUNG_ZUSAETZLICH_MSB: return "ABLESUNG_ZUSAETZLICH_MSB";
            case AUSLESUNG_2_X_TAEGLICH_FERNAUSLESUNG: return "AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG";
            case AUSLESUNG_FERNAUSLESUNG: return "AUSLESUNG_FERNAUSLESUNG";
            case AUSLESUNG_FERNAUSLESUNG_ZUSAETZLICH_MSB: return "AUSLESUNG_FERNAUSLESUNG_ZUSAETZLICH_MSB";
            case AUSLESUNG_JAEHRLICH_FERNAUSLESUNG: return "AUSLESUNG_JAEHRLICH_FERNAUSLESUNG";
            case AUSLESUNG_KOMPAKTMENGENUMWERTER: return "AUSLESUNG_KOMPAKTMENGENUMWERTER";
            case AUSLESUNG_MANUELL_MSB: return "AUSLESUNG_MANUELL_MSB";
            case AUSLESUNG_MDE: return "AUSLESUNG_MDE";
            case AUSLESUNG_MOATLICH_FERNAUSLESUNG: return "AUSLESUNG_MOATLICH_FERNAUSLESUNG";
            case AUSLESUNG_MONATLICH_FERNAUSLESUNG: return "AUSLESUNG_MONATLICH_FERNAUSLESUNG";
            case AUSLESUNG_STUENDLICH_FERNAUSLESUNG: return "AUSLESUNG_STUENDLICH_FERNAUSLESUNG";
            case AUSLESUNG_SYSTEMMENGENUMWERTER: return "AUSLESUNG_SYSTEMMENGENUMWERTER";
            case AUSLESUNG_TAEGLICH_FERNAUSLESUNG: return "AUSLESUNG_TAEGLICH_FERNAUSLESUNG";
            case AUSLESUNG_TEMPERATURMENGENUMWERTER: return "AUSLESUNG_TEMPERATURMENGENUMWERTER";
            case AUSLESUNG_VORGANG: return "AUSLESUNG_VORGANG";
            case AUSLESUNG_ZUSTANDSMENGENUMWERTER: return "AUSLESUNG_ZUSTANDSMENGENUMWERTER";
            case DATENBEREITSTELLUNG_EINMALIG: return "DATENBEREITSTELLUNG_EINMALIG";
            case DATENBEREITSTELLUNG_HALBJAEHRLICH: return "DATENBEREITSTELLUNG_HALBJAEHRLICH";
            case DATENBEREITSTELLUNG_HISTORISCHE_LG: return "DATENBEREITSTELLUNG_HISTORISCHE_LG";
            case DATENBEREITSTELLUNG_JAEHRLICH: return "DATENBEREITSTELLUNG_JAEHRLICH";
            case DATENBEREITSTELLUNG_MONATLICH: return "DATENBEREITSTELLUNG_MONATLICH";
            case DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH: return "DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH";
            case DATENBEREITSTELLUNG_STUENDLICH: return "DATENBEREITSTELLUNG_STUENDLICH";
            case DATENBEREITSTELLUNG_TAEGLICH: return "DATENBEREITSTELLUNG_TAEGLICH";
            case DATENBEREITSTELLUNG_VIERTELJAEHRLICH: return "DATENBEREITSTELLUNG_VIERTELJAEHRLICH";
            case DATENBEREITSTELLUNG_WOECHENTLICH: return "DATENBEREITSTELLUNG_WOECHENTLICH";
            case ENTSPERRUNG: return "ENTSPERRUNG";
            case INKASSOKOSTEN: return "INKASSOKOSTEN";
            case MAHNKOSTEN: return "MAHNKOSTEN";
            case SPERRUNG: return "SPERRUNG";
        }
        return null;
    }

    public static Dienstleistungstyp forValue(String value) throws IOException {
        if (value.equals("ABLESUNG_HALBJAEHRLICH")) return ABLESUNG_HALBJAEHRLICH;
        if (value.equals("ABLESUNG_JAEHRLICH")) return ABLESUNG_JAEHRLICH;
        if (value.equals("ABLESUNG_MONATLICH")) return ABLESUNG_MONATLICH;
        if (value.equals("ABLESUNG_VIERTELJAEHRLICH")) return ABLESUNG_VIERTELJAEHRLICH;
        if (value.equals("ABLESUNG_ZUSAETZLICH_KUNDE")) return ABLESUNG_ZUSAETZLICH_KUNDE;
        if (value.equals("ABLESUNG_ZUSAETZLICH_MSB")) return ABLESUNG_ZUSAETZLICH_MSB;
        if (value.equals("AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG")) return AUSLESUNG_2_X_TAEGLICH_FERNAUSLESUNG;
        if (value.equals("AUSLESUNG_FERNAUSLESUNG")) return AUSLESUNG_FERNAUSLESUNG;
        if (value.equals("AUSLESUNG_FERNAUSLESUNG_ZUSAETZLICH_MSB")) return AUSLESUNG_FERNAUSLESUNG_ZUSAETZLICH_MSB;
        if (value.equals("AUSLESUNG_JAEHRLICH_FERNAUSLESUNG")) return AUSLESUNG_JAEHRLICH_FERNAUSLESUNG;
        if (value.equals("AUSLESUNG_KOMPAKTMENGENUMWERTER")) return AUSLESUNG_KOMPAKTMENGENUMWERTER;
        if (value.equals("AUSLESUNG_MANUELL_MSB")) return AUSLESUNG_MANUELL_MSB;
        if (value.equals("AUSLESUNG_MDE")) return AUSLESUNG_MDE;
        if (value.equals("AUSLESUNG_MOATLICH_FERNAUSLESUNG")) return AUSLESUNG_MOATLICH_FERNAUSLESUNG;
        if (value.equals("AUSLESUNG_MONATLICH_FERNAUSLESUNG")) return AUSLESUNG_MONATLICH_FERNAUSLESUNG;
        if (value.equals("AUSLESUNG_STUENDLICH_FERNAUSLESUNG")) return AUSLESUNG_STUENDLICH_FERNAUSLESUNG;
        if (value.equals("AUSLESUNG_SYSTEMMENGENUMWERTER")) return AUSLESUNG_SYSTEMMENGENUMWERTER;
        if (value.equals("AUSLESUNG_TAEGLICH_FERNAUSLESUNG")) return AUSLESUNG_TAEGLICH_FERNAUSLESUNG;
        if (value.equals("AUSLESUNG_TEMPERATURMENGENUMWERTER")) return AUSLESUNG_TEMPERATURMENGENUMWERTER;
        if (value.equals("AUSLESUNG_VORGANG")) return AUSLESUNG_VORGANG;
        if (value.equals("AUSLESUNG_ZUSTANDSMENGENUMWERTER")) return AUSLESUNG_ZUSTANDSMENGENUMWERTER;
        if (value.equals("DATENBEREITSTELLUNG_EINMALIG")) return DATENBEREITSTELLUNG_EINMALIG;
        if (value.equals("DATENBEREITSTELLUNG_HALBJAEHRLICH")) return DATENBEREITSTELLUNG_HALBJAEHRLICH;
        if (value.equals("DATENBEREITSTELLUNG_HISTORISCHE_LG")) return DATENBEREITSTELLUNG_HISTORISCHE_LG;
        if (value.equals("DATENBEREITSTELLUNG_JAEHRLICH")) return DATENBEREITSTELLUNG_JAEHRLICH;
        if (value.equals("DATENBEREITSTELLUNG_MONATLICH")) return DATENBEREITSTELLUNG_MONATLICH;
        if (value.equals("DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH")) return DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH;
        if (value.equals("DATENBEREITSTELLUNG_STUENDLICH")) return DATENBEREITSTELLUNG_STUENDLICH;
        if (value.equals("DATENBEREITSTELLUNG_TAEGLICH")) return DATENBEREITSTELLUNG_TAEGLICH;
        if (value.equals("DATENBEREITSTELLUNG_VIERTELJAEHRLICH")) return DATENBEREITSTELLUNG_VIERTELJAEHRLICH;
        if (value.equals("DATENBEREITSTELLUNG_WOECHENTLICH")) return DATENBEREITSTELLUNG_WOECHENTLICH;
        if (value.equals("ENTSPERRUNG")) return ENTSPERRUNG;
        if (value.equals("INKASSOKOSTEN")) return INKASSOKOSTEN;
        if (value.equals("MAHNKOSTEN")) return MAHNKOSTEN;
        if (value.equals("SPERRUNG")) return SPERRUNG;
        throw new IOException("Cannot deserialize Dienstleistungstyp");
    }
}
