package com.example.bo4e.enums;

import java.io.IOException;

/**
 * Aufzählung von zusätzlichen Informationen zum Status, beispielsweise in Lastgängen oder
 * Zählwerkständen.
 */
public enum Messwertstatuszusatz {
    Z74_KEINZUGANG, Z75_KOMMUNIKATIONSSTOERUNG, Z76_NETZAUSFALL, Z77_SPANNUNGSAUSFALL, Z78_GERAETEWECHSEL, Z79_KALIBRIERUNG, Z80_GERAETARBEITETAUSSERHALBDERBETRIEBSBEDINGUNGEN, Z81_MESSEINRICHTUNGGESTOERT_DEFEKT, Z82_UNSICHERHEITMESSUNG, Z84_LEERSTAND, Z85_REALERZAEHLERUEBERLAUFGEPRUEFT, Z86_PLAUSIBELWGKONTROLLABLESUNG, Z87_PLAUSIBELWGKUNDENHINWEIS, Z88_VERGLEICHSMESSUNG_GEEICHT, Z89_VERGLEICHSMESSUNG_NICHTGEEICHT, Z90_MESSWERTNACHBILDUNGAUSGEEICHTENWERTEN, Z91_MESSWERTNACHBILDUNGAUSNICHTGEEICHTENWERTEN, Z92_INTERPOLATION, Z93_HALTEWERT, Z94_BILANZIERUNGNETZABSCHNITT, Z95_HISTORISCHEMESSWERTE, Z98_BERUECKSICHTIGUNGSTOERMENGENZAEHLWERK, Z99_MENGENUMWERTUNGUNVOLLSTAENDIG, ZA0_UHRZEITGESTELLT_SYNCHRONISATION, ZA1_MESSWERTUNPLAUSIBEL, ZA3_FALSCHERWANDLERFAKTOR, ZA4_FEHLERHAFTEABLESUNG, ZA5_AENDERUNGDERBERECHNUNG, ZA6_UMBAUDERMESSLOKATION, ZA7_DATENBEARBEITUNGSFEHLER, ZA8_BRENNWERTKORREKTUR, ZA9_Z_ZAHL_KORREKTUR, ZB0_STOERUNG_DEFEKTMESSEINRICHTUNG, ZB9_AENDERUNGTARIFSCHALTZEITEN, ZC2_TARIFSCHALTGERAETDEFEKT, ZC3_AUSTAUSCHDESERSATZWERTES, ZC4_IMPULSWERTIGKEITNICHTAUSREICHEND, ZG3_UMSTELLUNGGASQUALITAET, ZJ2_STATISTISCHEMETHODE;

    public String toValue() {
        switch (this) {
            case Z74_KEINZUGANG: return "Z74_KEINZUGANG";
            case Z75_KOMMUNIKATIONSSTOERUNG: return "Z75_KOMMUNIKATIONSSTOERUNG";
            case Z76_NETZAUSFALL: return "Z76_NETZAUSFALL";
            case Z77_SPANNUNGSAUSFALL: return "Z77_SPANNUNGSAUSFALL";
            case Z78_GERAETEWECHSEL: return "Z78_GERAETEWECHSEL";
            case Z79_KALIBRIERUNG: return "Z79_KALIBRIERUNG";
            case Z80_GERAETARBEITETAUSSERHALBDERBETRIEBSBEDINGUNGEN: return "Z80_GERAETARBEITETAUSSERHALBDERBETRIEBSBEDINGUNGEN";
            case Z81_MESSEINRICHTUNGGESTOERT_DEFEKT: return "Z81_MESSEINRICHTUNGGESTOERT_DEFEKT";
            case Z82_UNSICHERHEITMESSUNG: return "Z82_UNSICHERHEITMESSUNG";
            case Z84_LEERSTAND: return "Z84_LEERSTAND";
            case Z85_REALERZAEHLERUEBERLAUFGEPRUEFT: return "Z85_REALERZAEHLERUEBERLAUFGEPRUEFT";
            case Z86_PLAUSIBELWGKONTROLLABLESUNG: return "Z86_PLAUSIBELWGKONTROLLABLESUNG";
            case Z87_PLAUSIBELWGKUNDENHINWEIS: return "Z87_PLAUSIBELWGKUNDENHINWEIS";
            case Z88_VERGLEICHSMESSUNG_GEEICHT: return "Z88_VERGLEICHSMESSUNG(GEEICHT)";
            case Z89_VERGLEICHSMESSUNG_NICHTGEEICHT: return "Z89_VERGLEICHSMESSUNG(NICHTGEEICHT)";
            case Z90_MESSWERTNACHBILDUNGAUSGEEICHTENWERTEN: return "Z90_MESSWERTNACHBILDUNGAUSGEEICHTENWERTEN";
            case Z91_MESSWERTNACHBILDUNGAUSNICHTGEEICHTENWERTEN: return "Z91_MESSWERTNACHBILDUNGAUSNICHTGEEICHTENWERTEN";
            case Z92_INTERPOLATION: return "Z92_INTERPOLATION";
            case Z93_HALTEWERT: return "Z93_HALTEWERT";
            case Z94_BILANZIERUNGNETZABSCHNITT: return "Z94_BILANZIERUNGNETZABSCHNITT";
            case Z95_HISTORISCHEMESSWERTE: return "Z95_HISTORISCHEMESSWERTE";
            case Z98_BERUECKSICHTIGUNGSTOERMENGENZAEHLWERK: return "Z98_BERUECKSICHTIGUNGSTOERMENGENZAEHLWERK";
            case Z99_MENGENUMWERTUNGUNVOLLSTAENDIG: return "Z99_MENGENUMWERTUNGUNVOLLSTAENDIG";
            case ZA0_UHRZEITGESTELLT_SYNCHRONISATION: return "ZA0_UHRZEITGESTELLT_SYNCHRONISATION";
            case ZA1_MESSWERTUNPLAUSIBEL: return "ZA1_MESSWERTUNPLAUSIBEL";
            case ZA3_FALSCHERWANDLERFAKTOR: return "ZA3_FALSCHERWANDLERFAKTOR";
            case ZA4_FEHLERHAFTEABLESUNG: return "ZA4_FEHLERHAFTEABLESUNG";
            case ZA5_AENDERUNGDERBERECHNUNG: return "ZA5_AENDERUNGDERBERECHNUNG";
            case ZA6_UMBAUDERMESSLOKATION: return "ZA6_UMBAUDERMESSLOKATION";
            case ZA7_DATENBEARBEITUNGSFEHLER: return "ZA7_DATENBEARBEITUNGSFEHLER";
            case ZA8_BRENNWERTKORREKTUR: return "ZA8_BRENNWERTKORREKTUR";
            case ZA9_Z_ZAHL_KORREKTUR: return "ZA9_Z-ZAHL-KORREKTUR";
            case ZB0_STOERUNG_DEFEKTMESSEINRICHTUNG: return "ZB0_STOERUNG_DEFEKTMESSEINRICHTUNG";
            case ZB9_AENDERUNGTARIFSCHALTZEITEN: return "ZB9_AENDERUNGTARIFSCHALTZEITEN";
            case ZC2_TARIFSCHALTGERAETDEFEKT: return "ZC2_TARIFSCHALTGERAETDEFEKT";
            case ZC3_AUSTAUSCHDESERSATZWERTES: return "ZC3_AUSTAUSCHDESERSATZWERTES";
            case ZC4_IMPULSWERTIGKEITNICHTAUSREICHEND: return "ZC4_IMPULSWERTIGKEITNICHTAUSREICHEND";
            case ZG3_UMSTELLUNGGASQUALITAET: return "ZG3_UMSTELLUNGGASQUALITAET";
            case ZJ2_STATISTISCHEMETHODE: return "ZJ2_STATISTISCHEMETHODE";
        }
        return null;
    }

    public static Messwertstatuszusatz forValue(String value) throws IOException {
        if (value.equals("Z74_KEINZUGANG")) return Z74_KEINZUGANG;
        if (value.equals("Z75_KOMMUNIKATIONSSTOERUNG")) return Z75_KOMMUNIKATIONSSTOERUNG;
        if (value.equals("Z76_NETZAUSFALL")) return Z76_NETZAUSFALL;
        if (value.equals("Z77_SPANNUNGSAUSFALL")) return Z77_SPANNUNGSAUSFALL;
        if (value.equals("Z78_GERAETEWECHSEL")) return Z78_GERAETEWECHSEL;
        if (value.equals("Z79_KALIBRIERUNG")) return Z79_KALIBRIERUNG;
        if (value.equals("Z80_GERAETARBEITETAUSSERHALBDERBETRIEBSBEDINGUNGEN")) return Z80_GERAETARBEITETAUSSERHALBDERBETRIEBSBEDINGUNGEN;
        if (value.equals("Z81_MESSEINRICHTUNGGESTOERT_DEFEKT")) return Z81_MESSEINRICHTUNGGESTOERT_DEFEKT;
        if (value.equals("Z82_UNSICHERHEITMESSUNG")) return Z82_UNSICHERHEITMESSUNG;
        if (value.equals("Z84_LEERSTAND")) return Z84_LEERSTAND;
        if (value.equals("Z85_REALERZAEHLERUEBERLAUFGEPRUEFT")) return Z85_REALERZAEHLERUEBERLAUFGEPRUEFT;
        if (value.equals("Z86_PLAUSIBELWGKONTROLLABLESUNG")) return Z86_PLAUSIBELWGKONTROLLABLESUNG;
        if (value.equals("Z87_PLAUSIBELWGKUNDENHINWEIS")) return Z87_PLAUSIBELWGKUNDENHINWEIS;
        if (value.equals("Z88_VERGLEICHSMESSUNG(GEEICHT)")) return Z88_VERGLEICHSMESSUNG_GEEICHT;
        if (value.equals("Z89_VERGLEICHSMESSUNG(NICHTGEEICHT)")) return Z89_VERGLEICHSMESSUNG_NICHTGEEICHT;
        if (value.equals("Z90_MESSWERTNACHBILDUNGAUSGEEICHTENWERTEN")) return Z90_MESSWERTNACHBILDUNGAUSGEEICHTENWERTEN;
        if (value.equals("Z91_MESSWERTNACHBILDUNGAUSNICHTGEEICHTENWERTEN")) return Z91_MESSWERTNACHBILDUNGAUSNICHTGEEICHTENWERTEN;
        if (value.equals("Z92_INTERPOLATION")) return Z92_INTERPOLATION;
        if (value.equals("Z93_HALTEWERT")) return Z93_HALTEWERT;
        if (value.equals("Z94_BILANZIERUNGNETZABSCHNITT")) return Z94_BILANZIERUNGNETZABSCHNITT;
        if (value.equals("Z95_HISTORISCHEMESSWERTE")) return Z95_HISTORISCHEMESSWERTE;
        if (value.equals("Z98_BERUECKSICHTIGUNGSTOERMENGENZAEHLWERK")) return Z98_BERUECKSICHTIGUNGSTOERMENGENZAEHLWERK;
        if (value.equals("Z99_MENGENUMWERTUNGUNVOLLSTAENDIG")) return Z99_MENGENUMWERTUNGUNVOLLSTAENDIG;
        if (value.equals("ZA0_UHRZEITGESTELLT_SYNCHRONISATION")) return ZA0_UHRZEITGESTELLT_SYNCHRONISATION;
        if (value.equals("ZA1_MESSWERTUNPLAUSIBEL")) return ZA1_MESSWERTUNPLAUSIBEL;
        if (value.equals("ZA3_FALSCHERWANDLERFAKTOR")) return ZA3_FALSCHERWANDLERFAKTOR;
        if (value.equals("ZA4_FEHLERHAFTEABLESUNG")) return ZA4_FEHLERHAFTEABLESUNG;
        if (value.equals("ZA5_AENDERUNGDERBERECHNUNG")) return ZA5_AENDERUNGDERBERECHNUNG;
        if (value.equals("ZA6_UMBAUDERMESSLOKATION")) return ZA6_UMBAUDERMESSLOKATION;
        if (value.equals("ZA7_DATENBEARBEITUNGSFEHLER")) return ZA7_DATENBEARBEITUNGSFEHLER;
        if (value.equals("ZA8_BRENNWERTKORREKTUR")) return ZA8_BRENNWERTKORREKTUR;
        if (value.equals("ZA9_Z-ZAHL-KORREKTUR")) return ZA9_Z_ZAHL_KORREKTUR;
        if (value.equals("ZB0_STOERUNG_DEFEKTMESSEINRICHTUNG")) return ZB0_STOERUNG_DEFEKTMESSEINRICHTUNG;
        if (value.equals("ZB9_AENDERUNGTARIFSCHALTZEITEN")) return ZB9_AENDERUNGTARIFSCHALTZEITEN;
        if (value.equals("ZC2_TARIFSCHALTGERAETDEFEKT")) return ZC2_TARIFSCHALTGERAETDEFEKT;
        if (value.equals("ZC3_AUSTAUSCHDESERSATZWERTES")) return ZC3_AUSTAUSCHDESERSATZWERTES;
        if (value.equals("ZC4_IMPULSWERTIGKEITNICHTAUSREICHEND")) return ZC4_IMPULSWERTIGKEITNICHTAUSREICHEND;
        if (value.equals("ZG3_UMSTELLUNGGASQUALITAET")) return ZG3_UMSTELLUNGGASQUALITAET;
        if (value.equals("ZJ2_STATISTISCHEMETHODE")) return ZJ2_STATISTISCHEMETHODE;
        throw new IOException("Cannot deserialize Messwertstatuszusatz");
    }
}
